### ISSUE TITLE
Logo changes

### ISSUE THREAD

**Issue by hadiasghari** [datarights/DataInSight#102]
add beta to the Logo.

**Comment by hadiasghari** [comment]
@postdigital can we also have another logo stating 'DataInSight'?  (so we can swap if we want)

**Comment by postdigital** [comment]
Here are the two logo's with BETA for 'datarights' and 'datainsight' in .svg format, ready to be replaced on the website: [logos.zip](https://github.com/datarights/DataInSight/files/1819716/logos.zip)
I already did that on the info page www.datarights.me
