### ISSUE TITLE
Some shifting and changing of UX parts

### ISSUE THREAD

**Issue by hadiasghari** [datarights/DataInSight#103]
- 2FA: shows to all users during login; it should be only if user has it enabled.
- During sign-up, inform user they can later on set up 2FA OR take user to profile page after sign-up (so they can enter address and such information)
- My profile: should move next to welcome/name
- Notification settings: should be moved next to notifications; 
- On joint campagin page with consent: don't show notifications 
- Remove Home button (our logo does that)
- Once logged in, on the home/campaigns page, the user should see the stats of the system (same as the ones shown on the login screen)
- For now, remove language for users (only leave it for admin for testing)

**Comment by mani47** [comment]
Login shows 2FA only if user has it enabled: e42065e571d150e74120b937c260590ee23a6830

**Comment by hadiasghari** [comment]
some parts moved to other issues; all of above seems to be done except this:

When joining a campagin, the consent page should NOT include notification settings
