### ISSUE TITLE
Move staging server to TUDelft servers

### ISSUE THREAD

**Issue by mani47** [datarights/DataInSight#106]
In order to make testing between Staging and Production consistent we should migrate staging servers from Heroku to TUDelft servers.

**Comment by hadiasghari** [comment]
@mani47 is this planned for this week's release or later? thanks!

**Comment by mani47** [comment]
Later because I have already a lot on my plate but I will try to do it before the end of the march so we can switch to the free plan of Heroku.

**Comment by hadiasghari** [comment]
@mani47 is this already done? was scheduled for beta2. if done let's close it.
