### ISSUE TITLE
Attachments: multiple & blacking out

### ISSUE THREAD

**Issue by hadiasghari** [datarights/DataInSight#109]
- We need a way to upload multiple attachments for an access responses. This is a quite common scenario (consider users scanning separate photos of received documents with their phone; or if they receive a separate batch of documents at a later date).

- The PDF viewer and blackout tool seem to fail on large very large PDFs. For instance: https://www.studyinholland.nl/documentation/holland-scholarship.pdf

- Btw, on the attachments upload form (wherever it ends up being), there is no need for a separate "I want to blackout" checkbox, why not instead always take the user for a blackout?

**Comment by postdigital** [comment]
- The issue of not being able to upload more attachments per status update has been raised earlier by me in conversations with Mani, but we decided to let it go for now and leave that to the user (a scanning app on the phone can bundle many pictures/scans into one PDF). I know that it raises some concerns, but - on the other hand - the use can always upload a document per status update, so he/she can just create a new status when receiving new documents later etc etc. In short, there is possibility to upload many attachments, but only one per status update. I think this can work. Do you strongly disagree?

- Always going to the blackout tool is not that handy I think as it's not integrated that well with the platform. I mean, in the way it works. Some technical limitations occurred there... @mani47 maybe you can explain this better. Either way, I personally think skipping the blackout tool is OK.

**Comment by hadiasghari** [comment]
@postdigital forcing users to use one PDF could add unnecessary time to what user's need to do. I know our DB supports more files; why not add the feature?

Re the blackout tool:  if the tool doesn't work, shouldn't we remove it? Or place it in a separate place, outside of the workflow?

**Comment by hadiasghari** [comment]
@mani47 I suggest we move out the blackout tool for now; just keep in the multiple attachments which is a must

**Comment by hadiasghari** [comment]
Multiple attachment fixed by @mani47 ; some UX improvements possibles; blackout disabled, to be renabled in later versions.

**Comment by hadiasghari** [comment]
moved into other tasks in MT.
