### ISSUE TITLE
Template in multiple language + translation

### ISSUE THREAD

**Issue by hadiasghari** [datarights/DataInSight#112]
For the starting campaign, I need an easy way to allow users to choose their template letters to be either Dutch or English. (Currently this setting is set to be decided automatically from the company address or user's profile settings -- which are good for 'defaults' but rather confusing not to have the possibility to change). 

Possibly the form should include a dropdown with templates relevant for this state of the work-flow with some default selected. But it could also be the choices are shown in the radio button list.

Also: we need to be able to show a link (to our forum or wiki) that offers background on a template or it's translation; (the original idea I recall was to have per paragraph tips set in the template engine -- this might be a start.)

**Comment by mani47** [comment]
fixed in #5c3689462e26cd0c5577643fd784acf329cf7fa3 and released on both Heroku and TU servers.
