### ISSUE TITLE
Workflow: engine revisions

### ISSUE THREAD

**Issue by hadiasghari** [datarights/DataInSight#121]
As discussed on 18-03-2018, a number of changes related to the workflow:

- in transitions: don't show 'timeout' (systemic ones); 
- allow ordering list of transitions (or events)
- possible removal of events
- addition of a response object (where we can describe the response)
- in UX: don't show 'undo' visuals as a rectangle box 
- in UX: triangle should rotate when AR history is shown
- workflow button color & text should be in database

**Comment by mani47** [comment]
- Added transition_type (event, undo, timeout), user only see 'event' type transitions.
- Added display_order to transitions.
- Possible removal of events? Can you explain more? We are just showing the events in what_happened_update_status form, we can replace it with another form and don't show the design. Things are still very blurry for me regarding your desired UX.
- Addition of a response object: Is In progress ... What about UI where we should get this responses from user? A link like add attachment that says "Add/Upload response"?
-  in UX: triangle should rotate when AR history is shown: I will make this a separate issue and will assign it to @postdigital .
-  workflow button color & text should be in database: Standard bootstrap CSS classes are available: https://getbootstrap.com/docs/4.0/components/buttons/
