### ISSUE TITLE
Disable signup except for..

### ISSUE THREAD

**Issue by hadiasghari** [datarights/DataInSight#126]
I'd like for people signing up to get a message that they will be notified when ready. (I guess they would need to provide some remark about their interests too)
Admin can approve users (one-by-one) via backend. (some email notification of new signup would help)
Exceptions: if user's email is from @student.tudelft.nl  or @tudelft.nl, then automatically confirm.

**Comment by mani47** [comment]
Admin > General > Settings there is a setting key named "auto_approved_user_domains" which is Comma seperated list of domains that do not need any admin approval for sign up. * means all domains are allowed and auto approved.

In your case: "@student.tudelft.nl, @tudelft.nl" will work.
