### ISSUE TITLE
Triangle click

### ISSUE THREAD

**Issue by hadiasghari** [datarights/DataInSight#134]
@postdigital the triangle button when the access request is expanded needs to rotate/change to one facing down. Without that the UX is confusing.

As @mani47 pointed out earlier this need to be fixed in HTML/Bootstrap side. So could you kindly fix this?

(I suggested perhaps a unicode triangle character might work better than images if we are using images).

**Comment by postdigital** [comment]
@mani47 , here is a simple fix for that:

1. This line should be removed:
`<img src="Entypo+/controller-play.svg" height="24" align="left" alt="">`

2. This JS line should be added:
`<script>
$(document).ready(function(){
    $(".nonselect").click(function(){
        $(this).toggleClass("select");
    });
});
</script>`

3. This should added to CSS:
`.nonselect::before {
			 content: "▸ ";
		}		
.select::before { 
    content: "▾ "; 
	
}`
