### ISSUE TITLE
New Access Request Form

### ISSUE THREAD

**Issue by hadiasghari** [datarights/DataInSight#138]
1. Combine the "create new access request" form and "upload existing access request form".

2. The form should NOT ask for sending date or other information that are asked in the second step of the workflow.

3. Option to use request templates or own request (for templates: bring template list; for using own request: the user can then upload their file; this removes the need for separate form).

4. remove the option for 'standard/expanded' request: always be in expanded requests.

**Comment by hadiasghari** [comment]
@mani47 the "upload existing request" button is still there... did you upload it to staging?

**Comment by mani47** [comment]
Just released it to staging.
