### ISSUE TITLE
Simplifying Data Model Related to AcessRequest & its data

### ISSUE THREAD

**Issue by hadiasghari** [datarights/DataInSight#141]
To do as discussed with @mani47:

1. Merge london &  feature/incoming_outgoing_comm2 branches. This  renames WorkflowTransition to AccessRequestStep, converts SendingMethod to Enum, removes events & guards (since neither is/will-be used), and merges WorkflowVersion & Workflow (denormalized).

2. Create one Correspondence Object. This can either be a separate object with a one-to-one-link with ARStep. The object has the following fields (among others):
- correspondence date, 
- correspondence type (=enum, of what we have on responsetype)
- medium (=enum, post/email/call/weblink/meeting/other)
- direction (incoming or outgoing)
- has many attachments (or files)

3. Move fields holding correspondence of the sent request from AccessRequest -- and hold them in a a Correspondence object (with a corresponding initial ARStep or not, whatever is easiest).

4. Merge Workflow into AccessRequest (mainly the current-state).

5. Merge WorkflowType & WorkflowTypeVersion (denormalize them).

6. Rename Attachments to Documents. 

Thanks!

(CC @shahriarb FYI).

**Comment by mani47** [comment]
- Merged London branch into feature/incoming_outgoing_comm2 branch.
- Implemented string enums for sending method
- Created correspondence object with one on one link to ARSteps.
- Added new fields to correspondence object.

All of these changes are currently in feature/incoming_outgoing_comm2 branch.

**Comment by hadiasghari** [comment]
@mani47 ok thanks checked. still steps 4&5 are left. step 3 seems also left. from step 2: response-type enum still exists; attachment is still linked to ARStep still (should only go via correspondence if it means files)?

**Comment by hadiasghari** [comment]
Hi @mani47 steps 4 (merging WT & WTV) and  5 (merging AR & W)  are not done yet?

**Comment by hadiasghari** [comment]
@mani47 steps1-3 seem done, but steps 4 &  5 not so.
I am closing the request for now and will later open a separate one if needed.
