### ISSUE TITLE
Workflow: shouldn't download PDF when own template

### ISSUE THREAD

**Issue by hadiasghari** [datarights/DataInSight#142]
1. If a user uploads their OWN access request file in the create page, and then progresses to the next step, their PDF should NOT be downloaded again.

2. Note downloading also once happened in a later step when progressing from waiting for organization to waiting for user response ('something else' transition, blank form). Not sure if it's related or randomly caused by caching. 
3. Related bug: if no PDF is attached when choosing 'own', shouldn't really crash. Perhaps instead give an error and not proceed.

**Comment by mani47** [comment]
Fixed number 1 and 3, unable to reproduce number 2 probably a cache or that happens when you push the back button on browser.
