### ISSUE TITLE
Data Protection by Design

### ISSUE THREAD

**Issue by mani47** [datarights/DataInSight#36]
- PbD will be come mandatory from May 2018 according to EU law. But the law doesn't define what it means, and has left that to academia and industry to define the best practices. 
- JH's slides: https://www.cs.ru.nl/J.H.Hoepman/presentations/pds-2013.pdf
- JH's paper: https://arxiv.org/pdf/1210.6621.pdf

**Hadi thoughts:** of the 8 strategies above, four are data related (minimize/separate/abstract/hide), I think we meet all of these except from 'separation'  i.e. not having all our user data in one place (i.e. for a data breach). Of the four that are process related (inform/control/enforce/demonstrate), I think demonstrating will be the one to work on. 

(Similarly, we'd need to do a 'data protection impact assessment' at some point before going live)

**Comment by hadiasghari** [comment]
initital version has been prepared, we will continue working on it
