### ISSUE TITLE
Compact square logo needed for Forum

### ISSUE THREAD

**Issue by mani47** [datarights/DataInSight#74]
A compact version of your logo, shown at the top left of your site when scrolling down. Use a square shape.

About logo I think since Discourse is using D like a chat icon on their logo we can use the same idea for our forum logo, what do you think Pawel?

Also we need these icons and graphics:

Icons
Small Icon
Icon image used to represent your site in web browsers that looks good at small sizes such as 32px by 32px.
Upload 
Large Icon
Icon image used to represent your site on modern devices that looks good at larger sizes. Recommended size is at least 144px by 144px.

**Comment by postdigital** [comment]
Hi @mani47 , do you mean favicon? Here it is:
[favicon_datarightsme.zip](https://github.com/DataRights/MAPPED/files/1693367/favicon_datarightsme.zip)

**Comment by mani47** [comment]
@postdigital  Thanks for the favicon, But I meant the Discourse logo itself, are we going to use Discourse log instead of ours?

**Comment by postdigital** [comment]
@mani47 , ok, I got confused about that, because the logo of Discourse isn't really a square. The one in the top left corner is 244 x 66 pixels, right? Let's try this then:
![d-logo-sketch](https://user-images.githubusercontent.com/436937/35807038-cce6ed3e-0a81-11e8-8a38-1ef12805cb38.png)

**Comment by mani47** [comment]
The square logo is used when you scroll down on a post, for example If you go this page:

http://forum.datarights.me/t/assets-for-the-site-design/7

and scroll down you will see that square logo (which is just a D) on top.

**Comment by postdigital** [comment]
I'm not seeing it (sorry!)... Maybe you can take a screenshot for me? 
<img width="1259" alt="screen shot 2018-02-05 at 14 41 53" src="https://user-images.githubusercontent.com/436937/35807348-c5e57d6a-0a82-11e8-8bb6-32d169674943.png">

**Comment by mani47** [comment]
Pawel, You used a different account than postdigital and you were not admin, I made you admin so you should be able to see that page now.

**Comment by postdigital** [comment]
All right, I see... it is 66 x 66 px I see.  let's try this one for now:
![forum_logo](https://user-images.githubusercontent.com/436937/35807981-ad0aafde-0a84-11e8-8f78-9a69b0c3baf0.png)

Or here is a larger one, if needed?
![android-chrome-512x512](https://user-images.githubusercontent.com/436937/35808006-c15e9112-0a84-11e8-963a-f09431ac4095.png)
