### ISSUE TITLE
New access request: Liquid error shown where sending date should be

### ISSUE THREAD

**Issue by Rene-Mahieu** [datarights/DataInSight#96]
![screenshot from 2018-02-06 17-19-58](https://user-images.githubusercontent.com/26770254/35870486-145c6ea6-0b62-11e8-927e-3187bcd193ca.png)
See attached printscreen

**Comment by mani47** [comment]
That's a problem with rich text editor, if you go to the source tab it convets singe quote inside date to `{{&#39;today&#39;; | date: &#39;%Y-%m-%d&#39; }},` If you edit it in source and save it, it works.

**Comment by Rene-Mahieu** [comment]
@hadiasghari

**Comment by hadiasghari** [comment]
@Rene-Mahieu this is a bug that needs a change of the editor component to be fixed. For now, one option is to use Mani's workaround, which is to go to the 'source tab' and make the change he pointed out.

**Comment by hadiasghari** [comment]
Closing, same as #97
