### ISSUE TITLE
Unable to get rid of mistakes in the adress with the editor

### ISSUE THREAD

**Issue by Rene-Mahieu** [datarights/DataInSight#97]
![screenshot from 2018-02-06 17-54-37](https://user-images.githubusercontent.com/26770254/35872323-d52cac82-0b66-11e8-8758-3f34e0d37751.png)

Here I have a lot of white space between the different lines in the address between address line and postal code line. It is unclear for me what is causing this or how to solve it.

![screenshot from 2018-02-06 17-55-15](https://user-images.githubusercontent.com/26770254/35872369-f09e57c2-0b66-11e8-9ff5-60b2aedce67f.png)
Also, on the pdf preview, it shows that parts of the address such as addressee line ("privacy officer") which are on one line in the editor become two lines in the pdf

**Comment by mani47** [comment]
Hi Rene,

Unfortunately that's a problem must of rich text editors have, They generate additional html in the source and actually preview can differ. but It's easily solvable if you go into "source" tab of editor.
<img width="1163" alt="screen shot 2018-02-08 at 4 13 42 pm" src="https://user-images.githubusercontent.com/6079041/35972387-134a8090-0ceb-11e8-867b-953b3664a64b.png">

You can eliminate additional br tags (which stands for line breaks).

**Comment by hadiasghari** [comment]
For now we'll use the workaround suggested by Mani (here and in #97); for future we might change the editor

**Comment by hadiasghari** [comment]
merging into #144
