### ISSUE TITLE
Docker instructions fail

### ISSUE THREAD

**Issue by hadiasghari** [datarights/DataInSight#99]
Following the instructions on the README, I get stuck on step 7:

> $ docker-compose up
> Creating mapped_app_1 ... 
> Creating mapped_app_1 ... done
> Attaching to mapped_app_1
> app_1  | bundler: failed to load command: rails (/usr/local/bundle/bin/rails)
> app_1  | Bundler::GemfileNotFound: /usr/src/app/Gemfile not found
> app_1  |   /usr/local/lib/ruby/site_ruby/2.3.0/bundler/definition.rb:33:in `build'
> app_1  |   /usr/local/lib/ruby/site_ruby/2.3.0/bundler.rb:135:in `definition'
> app_1  |   /usr/local/lib/ruby/site_ruby/2.3.0/bundler.rb:101:in `setup'
> app_1  |   /usr/local/lib/ruby/site_ruby/2.3.0/bundler/setup.rb:20:in `<top (required)>'
> app_1  |   /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
> app_1  |   /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
> mapped_app_1 exited with code 1

(... and hence cannot continue with the next steps).  Any ideas?

**Comment by mani47** [comment]
Are you running `docker-compose build` and `docker-compose up` from root directory of our Github project? In docker-compose.yml file we have this line:
```

volumes:
    - .:/usr/src/app
```

This basically maps current working directory which should be root of our Github project with "Gemfile" to /usr/src/app looks like this process is failing somehow in your case and there is no Gemfile in /usr/src/app.

**Comment by hadiasghari** [comment]
Actually more generally: we want a deployment only (minimalistic) docker file too (without gstreamer etc)
